"""auto

Revision ID: 7172d4fbad79
Revises: 560811408406
Create Date: 2026-06-07 13:02:39.352690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7172d4fbad79'
down_revision: Union[str, Sequence[str], None] = '560811408406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: add column as nullable so existing rows are not violated
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    # Step 2: backfill existing rows with a default name derived from email
    op.execute(
        "UPDATE users SET name = split_part(email, '@', 1) WHERE name IS NULL"
    )
    # Step 3: enforce NOT NULL constraint going forward
    op.alter_column('users', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
